name: Docker Image CI

on:
  push:
   /*what is the branch*/
    branches:
      - master



jobs:
  build:
    /*what is the machine type*/
    runs-on: ubuntu-latest 
    /*array*/
    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo ahmed

/////////////////////////////////////////////////////
after creat yml file in github use git pull command 
/////////////////////////////////////////////////////
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
	/* will not download files on machine */
      - name: "before printing the folder containts"
        run: ls
	/* to download files using library or action اكشن جاهز */
      - uses: actions/checkout@v3

      - name: "after printing the folder containts"
        run: ls
$ why the .github folder not exists?
  as in linux any folder start with . is disappeard
	ls -a
////////////////////////////////////////////////////
to build image !!!!
	1- docker login 
	   docker login --username "" --password ""
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ali11 --password dckr_pat_53484obn9zPM_cmRsBftedTlw5w

$ it is not right as all people will see your username and password
        
///////////////////////////////////////////////////////
in github -> settings -> secrets -> actions
then press new repositery secret
put username
put the token 
in separate files

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
       
////////////////////////////////////////////////////////

build image and push it 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
      - name: " building docker "
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/docker-image-creation .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKER_USERNAME}}/docker-image-creation

/////////////////////////////////////////////////////////
task
