name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: hKFo2SBKRlpDaU10X3h3a19wdHRBeXk3TFdLOWVOYVRZZU1rMqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIHBqT1NxX281RklBWGl6cmJBOHh4eUxMeHc4TkxwMVZIo2NpZNkgbHZlOUdHbDhKdFNVcm5lUTFFVnVDMGxiakhkaTluYjk
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/myproject


      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myproject
